name: qiita_mitsuke_tatter

description: A Qiita Client App on Flutter.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  flutter_markdown: ^0.2.0
  url_launcher: ^5.0.2
  cupertino_icons: ^0.1.0
  equatable: ^0.2.3
  flutter_bloc: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
